# Generated by Django 4.2.2 on 2023-10-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_delete_author_book_image_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='no_image.JPEG', null=True, upload_to='book_images'),
        ),
    ]
