# Generated by Django 4.2.2 on 2023-10-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(choices=[('HORROR', 'horror'), ('COMEDY', 'comedy'), ('ROMANCE', 'romance'), ('ACTION', 'action'), ('SCI-FI', 'sci-fi'), ('SCIENCE', 'science')], max_length=20, verbose_name='the genre of this book'),
        ),
    ]
