# Generated by Django 4.2.2 on 2023-10-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(null=True, verbose_name='date the book was published'),
        ),
    ]
