# Generated by Django 4.2.2 on 2023-10-31 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='the isbn number of the book'),
        ),
    ]
