# Generated by Django 4.2.2 on 2023-11-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(help_text='author of the book', max_length=70, null=True),
        ),
    ]
